Repository thangved/flexible-rag, pull requests merged in 2024-10, with the labels that each got.

#8 ci(test): add testing func to github actions
  .github/workflows/ci.yml
  .python-version
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/sample.py
  tests/test_sample.py
Labels: ci/cd

#10 ci: update CI workflow to include pre-commit and Poetry installation
  .github/workflows/ci.yml
Labels: ci/cd

#11 Implement basic core features and APIs
  .env.example
  .pre-commit-config.yaml
  CHANGELOG.md
  Dockerfile
  api/__init__.py
  api/config.py
  api/dependencies.py
  api/main.py
  api/routes/__init__.py
  api/routes/vector_store.py
  compose.dev.yml
  core/__init__.py
  core/vector_store.py
  poetry.lock
  pyproject.toml
  tests/test_vector_store.py
Labels: enhancement

#14 feat: implement chat core
  api/dependencies.py
  api/main.py
  api/routes/chat_llm.py
  core/chat_llm.py
  tests/core/test_chat_llm.py
Labels: enhancement

#12 Implement core features and APIs
  .env.example
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .python-version
  CHANGELOG.md
  Dockerfile
  api/__init__.py
  api/config.py
  api/dependencies.py
  api/main.py
  api/routes/__init__.py
  api/routes/chat_llm.py
  api/routes/vector_store.py
  compose.dev.yml
  core/__init__.py
  core/chat_llm.py
  core/vector_store.py
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/api/__init__.py
  tests/api/test_main.py
  tests/core/__init__.py
  tests/core/test_chat_llm.py
  tests/core/test_vector_store.py
Labels: enhancement

#25 Implement Rerank Core and API
  Dockerfile
  api/dependencies.py
  api/main.py
  api/routes/rerank.py
  api/routes/vector_store.py
  compose.yml
  core/models/documents.py
  core/rerank.py
  core/vector_store.py
  tests/api/test_main.py
  tests/core/test_rerank.py
  tests/core/test_vector_store.py
  tests/fake/rerank.py
Labels: enhancement

#28 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#30 Create LICENSE
  LICENSE
Labels: documentation

#32 docs: init mkdocs project
  .github/workflows/docs.yml
  .pre-commit-config.yaml
  .vscode/settings.json
  docs/assets/logo.svg
  docs/blog/index.md
  docs/blog/posts/index.md
  docs/index.md
  docs/overrides/partials/comments.html
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: documentation

#33 docs: init mkdocs project
  .github/workflows/docs.yml
  .pre-commit-config.yaml
  .vscode/settings.json
  docs/assets/logo.svg
  docs/blog/index.md
  docs/blog/posts/index.md
  docs/index.md
  docs/overrides/partials/comments.html
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: documentation

#44 fix: change Dockerfile to exclude installing documentation dependencies
  Dockerfile
Labels: bug

#45 refactor: update CI workflow and documentation build process
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  build_openapi.py
  docs/api/.gitignore
  docs/api/restful.md
  docs/blog/.authors.yml
  docs/blog/posts/index.md
  docs/changelog/.gitkeep
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: documentation

#46 Develop
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  Dockerfile
  build_openapi.py
  docs/api/.gitignore
  docs/api/restful.md
  docs/blog/.authors.yml
  docs/blog/posts/index.md
  docs/changelog/.gitkeep
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: documentation

#51 fix: fix missing embedding_types
  Dockerfile
  api/dependencies.py
  compose.dev.yml
  compose.yml
Labels: bug

#52 Develop
  Dockerfile
  api/dependencies.py
  api/main.py
  build_openapi.py
  compose.dev.yml
  compose.yml
Labels: enhancement

#56 feat!: add reference_callback feature
  .idea/.gitignore
  .idea/flexible-rag.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  api/routes/vector_store.py
  compose.dev.yml
  core/vector_store.py
  tests/api/test_main.py
Labels: enhancement

#57 docs: add reference docs
  api/__init__.py
  api/dependencies.py
  api/routes/__init__.py
  core/__init__.py
  core/chat_llm.py
  core/models/__init__.py
  core/rerank.py
  core/vector_store.py
  mkdocs.yml
  poetry.lock
  pyproject.toml
  scripts/gen_ref_nav.py
  tests/fake/llm_chat.py
Labels: documentation

#65 ci: add docker ci
  .github/workflows/ci.yml
Labels: ci/cd
